### ISSUE TITLE
Adding /measures-values or compacting all value retrieval paths to one 

### ISSUE THREAD

**Issue by mohadelrezk** [OpenGovIntelligence/json-qb-api-implementation#3]
_From @mohadelrezk on December 2, 2016 11:1_

We have the following paths:
@Path("/dimension-values")
@Path("/attribute-values")

either we add @Path("/measure-values"), or compact the three paths to one as it uses same sparql query (getDimensionAttributeValues).

_Copied from original issue: zeginis/JSON-QB-REST-API#4_

**Comment by zeginis** [comment]
_From @mohadelrezk on December 2, 2016 11:14_

In the query for values of dim, attributes and measure distinct will influence data analysis results. 

_Copied from original issue: zeginis/JSON-QB-REST-API#7_

**Comment by zeginis** [comment]
The @Path("/dimension-values") @Path("/attribute-values") return the distinct values of a dimension/attribute. E.g for the sex dimension it will return: {male, female, all}

They are not ment to be used for data analysis but to get information about the dimensions and the values used.

For the analysis you should use @Path("/slice") or @Path("/table")
