### ISSUE TITLE
Adding available cubes path  

### ISSUE THREAD

**Issue by mohadelrezk** [OpenGovIntelligence/json-qb-api-implementation#4]
_From @mohadelrezk on December 2, 2016 11:4_

We need to explore available cubes (qb:DataSet or qb:DataStructureDefinition) before start queering for other cube contents.

_Copied from original issue: zeginis/JSON-QB-REST-API#5_

**Comment by mohadelrezk** [comment]
_From @zeginis on December 2, 2016 11:13_

What information do you need? I have (locally) implemented a method @Path("/cubes") that returns all available cubes at the store. Is this enough? Or you need something more?

I'll test the method and commit it soon!

**Comment by mohadelrezk** [comment]
this sound perfect, I have previously drafted this for our visualization: 
path:

/listLqbs?limit=500

results:

[{"description":"Real time meteorological and oceanographic data collected from the Irish moored Weather Buoy network of stations. Parameters collected include, DateTime (yyyy-mm-ddThh:mm:ss.sss), Atmospheric Pressure (mbar), Air Temperature (degreeCelsius), DewPoint Temperature (degreeCelsius), Wind Speed (knots), Max Gust Wind Speed (knots), Wind Direction (degreeTrue), Sea Surface Temperature (degreeCelsius), Wave Period (seconds), Wave Height (metres) and Relative Humidity (%). Real time data available for M2, M3, M4, M5 and M6. Historical data available for M1, FS1 and original M4 spatial location. Users of the download service can choose a station, time period, parameter(s) and output file type. Advanced download allows a user define a bounding box area of interest selecting one or more buoys from the network. 'NaN' or '-999' describes missing or unavailable data.","publisher":"http://ogi.eu/#Marine_Institute","comment":"Irish Weather Buoy Network data - extracted from Marine Institute ERDDAP Server","label":"Irish Weather Buoy Network","title":"Irish Weather Buoy Network","issued":"2016-08-11","dataset":"http://ogi.eu/#IWBNetwork_ds"},{"description":"Real time data and services of ocean wave information from moored wave buoys. Parameters collected include, dateTime (yyyy-mm-ddThh:mm:ss.sss), Peak Period (secs), Peak Direction (DegreesTrue), Upcross Period (secs) and Significant Wave Height (cm). Real time data available for Belmullet buoys and Galway Bay Wave Buoy. Historical data available for Galway Bay Wave Buoy 2. Users of the download service can choose a station, time period, parameter(s) and output file type. NaN or -999 describes missing or unavailable data.","publisher":"http://ogi.eu/#Marine_Institute","comment":"Irish Wave Buoys 30 Min Data - extracted from Marine Institute ERDDAP Server","label":"Irish Wave Buoys 30 Min","title":"Irish Wave Buoys 30 Min","issued":"2016-08-11","dataset":"http://ogi.eu/#IWaveBNetwork30Min_ds"},{"description":"The Irish National Tide Gauge Network is an on-going development involving the Marine Institute and a number of organisations in the public and private sectors to develop a permanent tidal monitoring infrastructure, ultimately consisting of between 35 and 40 stations.","publisher":"http://ogi.eu/#Marine_Institute","comment":"Irish National Tide Gauge Network data - extracted from Marine Institute ERDDAP Server","label":"Irish National Tide Gauge Network","title":"Irish National Tide Gauge Network","issued":"2016-08-11","dataset":"http://ogi.eu/#IrishNatoinalTideGaugeNetwork_ds"},{"description":"Resident population at the beginning of the year (persons by municipality)","publisher":"http://ogi.eu/#osp_stat_gov_lt","comment":"Resident population at the beginning of the year (persons by municipality)","label":"Resident population at the beginning of the year (persons by municipality)","title":"Resident population at the beginning of the year (persons by municipality)","issued":"2016-08-11","dataset":"http://ogi.eu/#RPBYmunicipality_ds"}]

**Comment by zeginis** [comment]
The @Path("/cubes")  returns a result containing the URI and labels of the cubes

At the current draft of the specifications there is a method "GET dataset-metadata" that returns all the metadata for a cube (this is not currently implemenet at the APi implementation)

Could possibly use a combination of these to to get the resutl you need?

**Comment by zeginis** [comment]
You can use a combination of:
- The @Path("/cubes") returns a result containing the URI and labels of the cubes
- The @Path("/dataset-metadata") returns all the metadata of a cube  including the label, title, description, comment, date issued, date modified, subject, publisher and license
