### ISSUE TITLE
service running errors

### ISSUE THREAD

**Issue by mohadelrezk** [OpenGovIntelligence/json-qb-api-implementation#8]
First, I add this jetty plugin to the pom file:

`<plugin>
 <groupId>org.eclipse.jetty</groupId>
<artifactId>jetty-maven-plugin</artifactId>
<version>9.4.0.RC1</version>
<configuration>
<war>${project.basedir}/target/JSON-QB-REST-API-0.0.1-SNAPSHOT.war</war>
</configuration>
</plugin>
`
when I try to run any of those mvn lines:

mvn clean install
or
mvn -Djetty.http.port=8088 jetty:run-war

I got the following compilation errors:

1- unmappable character for encoding UTF8 / at CubeSPARQL.java file
>solution was to open it using text editor and change the encoding to UTF8.

2-  
[ERROR] ~/src/org/certh/jsonqb/core/SPARQLresultTransformer.java:[9,52] package org.apache.lucene.analysis.util.CharArrayMap does not exist
> tried to add this dependency with versions 3.6.1 and 6.3.0 but still no luck :

`<dependency>
    <groupId>org.apache.lucene</groupId>
    <artifactId>lucene-core</artifactId>
    <version>0.0.0</version>
</dependency> 
`

**Comment by zeginis** [comment]
I changed encoding to UTF-8
And removed the useless import: org.apache.lucene.analysis.util.CharArrayMap

Can you checl if it is ok?

**Comment by mohadelrezk** [comment]
works fine now, thanks .
