### ISSUE TITLE
using (a) instead of rdf:type 

### ISSUE THREAD

**Issue by mohadelrezk** [OpenGovIntelligence/json-qb-api-implementation#9]
when using this link:
http://localhost:8088/cubes

I faced this error:

Fuseki - version 1.1.1 (Build date: 2014-10-02T16:36:17+0100)
org.eclipse.rdf4j.query.QueryEvaluationException: Error 400: Parse error: 
PREFIX qb: <http://purl.org/linked-data/cube#>PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>PREFIX skos: <http://www.w3.org/2004/02/skos/core#>PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>PREFIX opencube: <http://opencube-project.eu/> PREFIX dct: <http://purl.org/dc/terms/> select  distinct ?res where {?res rdf:type qb:DataSet }
Line 1, column 329: Unresolved prefixed name: rdf:type

we can avoid adding rdf prefix by using {?res a qb:DataSet }

**Comment by zeginis** [comment]
I added the rdf prefix to all SPARQL queries.

Can you check if it is ok?

**Comment by mohadelrezk** [comment]
I did the same locally, it is working.

I don't want to do a git pull as there is some refactoring in the package names not allowing compilation of the code, currently I am working on this commit (https://github.com/OpenGovIntelligence/json-qb-api-implementation/commit/efeca413c6b038d578dec82a16928cf6cd65c704) untill you finish refactoring.
